apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: "3.7.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    controller:
      image:
        digest: ''
        pullPolicy: Always
      podAnnotations:
        linkerd.io/inject: enabled
      config:
        server-tokens: "false"
        hide-headers: "Server"
        use-forwarded-headers: "true"
      # service:
      #   loadBalancerSourceRanges: ["0.0.0.0/0"]
      #   externalTrafficPolicy: "Local"
      #   loadBalancerIP: 212.2.246.58
      kind: Deployment
      minReadySeconds: 5
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "sleep 5; /usr/local/openresty/nginx/sbin/nginx -c /etc/nginx/nginx.conf -s quit; while pgrep -x nginx; do sleep 1; done"]
      terminationGracePeriodSeconds: 300