{{- if .Values.ingress -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "deployment.name" . -}}
{{- $servicePort := .Values.exposedPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "deployment.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "deployment.name" . }}
    helm.sh/chart: {{ include "deployment.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $servicePort }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
