### Identity Rotation keys and crt
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqVENDQVRTZ0F3SUJBZ0lSQUlGeHFkVDFFL2JlU3V3U0h0L05qNUl3Q2dZSUtvWkl6ajBFQXdJd0pURWoKTUNFR0ExVUVBeE1hY205dmRDNXNhVzVyWlhKa0xtTnNkWE4wWlhJdWJHOWpZV3d3SGhjTk1qRXdOREU1TVRVeQpNVFUwV2hjTk16RXdOREUzTVRVeU1UVTBXakFsTVNNd0lRWURWUVFERXhweWIyOTBMbXhwYm10bGNtUXVZMngxCmMzUmxjaTVzYjJOaGJEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJLelBZQUlRSGRDRjJUNXQKZ29KNUxVUytUMU9BRnVJd2NFd0dkMHNuY0lia1BESjVWSU5jTWZZUXdscXJTZjBHbnlzM2lHWG5ZYkh6STFtYQpBOGxYS1RTalJUQkRNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUJNQjBHCkExVWREZ1FXQkJTRkpBejRLc3RYVW9VZnAreXAwdVJTK3B1aml6QUtCZ2dxaGtqT1BRUURBZ05IQURCRUFpQUcKeXlRY1hmcjdGZ3FCWDFRQzQwalJtWmFhUFhiOUxwczhBTHo5L1Y0M25BSWdldDFOYnk3d01aTTA3MDhhVkc0VgpMVVBPREtkd1RPbTNtaHBIb2g4RkVObz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1sR0NreDhJTFRUb0U1YWl2UTc2UVBhbEFJUDM5YnJISzRNb1dESklENFFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFck05Z0FoQWQwSVhaUG0yQ2dua3RSTDVQVTRBVzRqQndUQVozU3lkd2h1UThNbmxVZzF3eAo5aERDV3F0Si9RYWZLemVJWmVkaHNmTWpXWm9EeVZjcE5BPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
type: kubernetes.io/tls

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 1h
  renewBefore: 5m
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
### Webhook keys and crts
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsRENDQVRxZ0F3SUJBZ0lSQU44aEc2YktKMURDdEhuN2NLQXNSKzh3Q2dZSUtvWkl6ajBFQXdJd0tERW0KTUNRR0ExVUVBeE1kZDJWaWFHOXZheTVzYVc1clpYSmtMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NakV3TkRFNQpNRGN3TkRBNVdoY05NekV3TkRFM01EY3dOREE1V2pBb01TWXdKQVlEVlFRREV4MTNaV0pvYjI5ckxteHBibXRsCmNtUXVZMngxYzNSbGNpNXNiMk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkZrcGg4bUsKK1YydmV4RUtmVUpMMTJsTFE0YTBTTlZxaW1VVVFvcG9RZjhzQWk2V3BtQnNHWDlKOTcxN0c0ZEptM0VWd1owegpoRlpWVGIyajFnaXpDQVNqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvCkFnRUJNQjBHQTFVZERnUVdCQlFFRkFqUURqVTVMRmNFRXluSCtzcFpWeTB1NGpBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpRUFsN1lBWXFWbWc1U2NuSHpYWlZTdDRPblRkaDA1LzF6WWlpRVRVYTYyOWZzQ0lEc2RHWVVsWmJUWApIcTViVWcwNWkzalpmU0lQSFg3c1BXQm1FWFc2aWdWQgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUo3UTBlQjFKUm1VVnQ5ZnRHdGRTNnovZGEyNG9yUXFQMU02b0hiaHk2QThvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFV1NtSHlZcjVYYTk3RVFwOVFrdlhhVXREaHJSSTFXcUtaUlJDaW1oQi95d0NMcGFtWUd3WgpmMG4zdlhzYmgwbWJjUlhCblRPRVZsVk52YVBXQ0xNSUJBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: webhook-issuer-tls
  namespace: linkerd
type: kubernetes.io/tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: linkerd
spec:
  ca:
    secretName: webhook-issuer-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc
  dnsNames:
  - linkerd-proxy-injector.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 1h
  renewBefore: 55m
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc
  dnsNames:
  - linkerd-sp-validator.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-tap
  namespace: linkerd
spec:
  secretName: linkerd-tap-k8s-tls
  duration: 1h
  renewBefore: 55m
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-tap.linkerd.svc
  dnsNames:
  - linkerd-tap.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
spec:
  releaseName: linkerd
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: "2.10.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    installNamespace: false
    identity:
      issuer: 
        scheme: kubernetes.io/tls

    identityTrustAnchorsPEM: |
      -----BEGIN CERTIFICATE-----
      MIIBjTCCATSgAwIBAgIRAIFxqdT1E/beSuwSHt/Nj5IwCgYIKoZIzj0EAwIwJTEj
      MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5MTUy
      MTU0WhcNMzEwNDE3MTUyMTU0WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
      c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKzPYAIQHdCF2T5t
      goJ5LUS+T1OAFuIwcEwGd0sncIbkPDJ5VINcMfYQwlqrSf0Gnys3iGXnYbHzI1ma
      A8lXKTSjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
      A1UdDgQWBBSFJAz4KstXUoUfp+yp0uRS+pujizAKBggqhkjOPQQDAgNHADBEAiAG
      yyQcXfr7FgqBX1QC40jRmZaaPXb9Lps8ALz9/V43nAIget1Nby7wMZM0708aVG4V
      LUPODKdwTOm3mhpHoh8FENo=
      -----END CERTIFICATE-----

    # webhook certificate keys
    proxyInjector:
      externalSecret: true 
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRAN8hG6bKJ1DCtHn7cKAsR+8wCgYIKoZIzj0EAwIwKDEm
        MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5
        MDcwNDA5WhcNMzEwNDE3MDcwNDA5WjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
        cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFkph8mK
        +V2vexEKfUJL12lLQ4a0SNVqimUUQopoQf8sAi6WpmBsGX9J9717G4dJm3EVwZ0z
        hFZVTb2j1gizCASjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBQEFAjQDjU5LFcEEynH+spZVy0u4jAKBggqhkjOPQQDAgNI
        ADBFAiEAl7YAYqVmg5ScnHzXZVSt4OnTdh05/1zYiiETUa629fsCIDsdGYUlZbTX
        Hq5bUg05i3jZfSIPHX7sPWBmEXW6igVB
        -----END CERTIFICATE-----
    
    profileValidator:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRAN8hG6bKJ1DCtHn7cKAsR+8wCgYIKoZIzj0EAwIwKDEm
        MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5
        MDcwNDA5WhcNMzEwNDE3MDcwNDA5WjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
        cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFkph8mK
        +V2vexEKfUJL12lLQ4a0SNVqimUUQopoQf8sAi6WpmBsGX9J9717G4dJm3EVwZ0z
        hFZVTb2j1gizCASjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBQEFAjQDjU5LFcEEynH+spZVy0u4jAKBggqhkjOPQQDAgNI
        ADBFAiEAl7YAYqVmg5ScnHzXZVSt4OnTdh05/1zYiiETUa629fsCIDsdGYUlZbTX
        Hq5bUg05i3jZfSIPHX7sPWBmEXW6igVB
        -----END CERTIFICATE-----
       
    tap:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRAN8hG6bKJ1DCtHn7cKAsR+8wCgYIKoZIzj0EAwIwKDEm
        MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5
        MDcwNDA5WhcNMzEwNDE3MDcwNDA5WjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
        cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFkph8mK
        +V2vexEKfUJL12lLQ4a0SNVqimUUQopoQf8sAi6WpmBsGX9J9717G4dJm3EVwZ0z
        hFZVTb2j1gizCASjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBQEFAjQDjU5LFcEEynH+spZVy0u4jAKBggqhkjOPQQDAgNI
        ADBFAiEAl7YAYqVmg5ScnHzXZVSt4OnTdh05/1zYiiETUa629fsCIDsdGYUlZbTX
        Hq5bUg05i3jZfSIPHX7sPWBmEXW6igVB
        -----END CERTIFICATE-----


