apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqVENDQVRPZ0F3SUJBZ0lRQ1VweHdYNGRoZ25Ka0pNdlFQZ1FTakFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1UQTBNVGt3TmpBeApOREZhRncwek1UQTBNVGN3TmpBeE5ERmFNQ1V4SXpBaEJnTlZCQU1UR25KdmIzUXViR2x1YTJWeVpDNWpiSFZ6CmRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXp1RUFJa2lxNGZMdGpzNFAKTmFGeHhiSlQ3T1Frc2QyanFzYVpIMXlCaGpFRDRGVUxvd3pIRGN1SDFqTkRiNzBJL1J3akVqcURVdE1ac0t3agp6bGJHSmFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXdIUVlEClZSME9CQllFRk41MldFcWV0c1RCYjBZcGNhRHVHU1ZhN1JaQk1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lHZFAKV1lXVlVFT3lxSkpoSXFGamNrcGx4T2xiMjIwTUZrYWFlQk15b25hZEFpRUE1eStybCt0VnFtMDltM1l0cVdvSgpscWI2dnR0QTArQ2tOMlpzaEVGT1lyTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdhUmtiSXZvOHNVYlNPaXBjQ2x5VmFsenJJdk50aWlVd2VXREtVRG4wUXpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFenVFQUlraXE0Zkx0anM0UE5hRnh4YkpUN09Ra3NkMmpxc2FaSDF5QmhqRUQ0RlVMb3d6SApEY3VIMWpORGI3MEkvUndqRWpxRFV0TVpzS3dqemxiR0pRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
type: kubernetes.io/tls
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 1h
  renewBefore: 55m
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
spec:
  releaseName: linkerd
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: "2.9.4"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    installNamespace: false
    identity:
      issuer: 
        scheme: kubernetes.io/tls
    global:
      identityTrustAnchorsPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBjTCCATOgAwIBAgIQCUpxwX4dhgnJkJMvQPgQSjAKBggqhkjOPQQDAjAlMSMw
        IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTA0MTkwNjAx
        NDFaFw0zMTA0MTcwNjAxNDFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
        dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzuEAIkiq4fLtjs4P
        NaFxxbJT7OQksd2jqsaZH1yBhjED4FULowzHDcuH1jNDb70I/RwjEjqDUtMZsKwj
        zlbGJaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
        VR0OBBYEFN52WEqetsTBb0YpcaDuGSVa7RZBMAoGCCqGSM49BAMCA0gAMEUCIGdP
        WYWVUEOyqJJhIqFjckplxOlb220MFkaaeBMyonadAiEA5y+rl+tVqm09m3YtqWoJ
        lqb6vttA0+CkN2ZshEFOYrM=
        -----END CERTIFICATE-----


