### Identity Rotation keys and crt
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqVENDQVRPZ0F3SUJBZ0lRQ1VweHdYNGRoZ25Ka0pNdlFQZ1FTakFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1UQTBNVGt3TmpBeApOREZhRncwek1UQTBNVGN3TmpBeE5ERmFNQ1V4SXpBaEJnTlZCQU1UR25KdmIzUXViR2x1YTJWeVpDNWpiSFZ6CmRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXp1RUFJa2lxNGZMdGpzNFAKTmFGeHhiSlQ3T1Frc2QyanFzYVpIMXlCaGpFRDRGVUxvd3pIRGN1SDFqTkRiNzBJL1J3akVqcURVdE1ac0t3agp6bGJHSmFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXdIUVlEClZSME9CQllFRk41MldFcWV0c1RCYjBZcGNhRHVHU1ZhN1JaQk1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lHZFAKV1lXVlVFT3lxSkpoSXFGamNrcGx4T2xiMjIwTUZrYWFlQk15b25hZEFpRUE1eStybCt0VnFtMDltM1l0cVdvSgpscWI2dnR0QTArQ2tOMlpzaEVGT1lyTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdhUmtiSXZvOHNVYlNPaXBjQ2x5VmFsenJJdk50aWlVd2VXREtVRG4wUXpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFenVFQUlraXE0Zkx0anM0UE5hRnh4YkpUN09Ra3NkMmpxc2FaSDF5QmhqRUQ0RlVMb3d6SApEY3VIMWpORGI3MEkvUndqRWpxRFV0TVpzS3dqemxiR0pRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
type: kubernetes.io/tls
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 1h
  renewBefore: 55m
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
### Webhook keys and crts
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsRENDQVRxZ0F3SUJBZ0lSQU44aEc2YktKMURDdEhuN2NLQXNSKzh3Q2dZSUtvWkl6ajBFQXdJd0tERW0KTUNRR0ExVUVBeE1kZDJWaWFHOXZheTVzYVc1clpYSmtMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NakV3TkRFNQpNRGN3TkRBNVdoY05NekV3TkRFM01EY3dOREE1V2pBb01TWXdKQVlEVlFRREV4MTNaV0pvYjI5ckxteHBibXRsCmNtUXVZMngxYzNSbGNpNXNiMk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkZrcGg4bUsKK1YydmV4RUtmVUpMMTJsTFE0YTBTTlZxaW1VVVFvcG9RZjhzQWk2V3BtQnNHWDlKOTcxN0c0ZEptM0VWd1owegpoRlpWVGIyajFnaXpDQVNqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvCkFnRUJNQjBHQTFVZERnUVdCQlFFRkFqUURqVTVMRmNFRXluSCtzcFpWeTB1NGpBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpRUFsN1lBWXFWbWc1U2NuSHpYWlZTdDRPblRkaDA1LzF6WWlpRVRVYTYyOWZzQ0lEc2RHWVVsWmJUWApIcTViVWcwNWkzalpmU0lQSFg3c1BXQm1FWFc2aWdWQgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUo3UTBlQjFKUm1VVnQ5ZnRHdGRTNnovZGEyNG9yUXFQMU02b0hiaHk2QThvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFV1NtSHlZcjVYYTk3RVFwOVFrdlhhVXREaHJSSTFXcUtaUlJDaW1oQi95d0NMcGFtWUd3WgpmMG4zdlhzYmgwbWJjUlhCblRPRVZsVk52YVBXQ0xNSUJBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: webhook-issuer-tls
  namespace: linkerd
type: kubernetes.io/tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: linkerd
spec:
  ca:
    secretName: webhook-issuer-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 1h
  renewBefore: 55m
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc
  dnsNames:
  - linkerd-proxy-injector.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 1h
  renewBefore: 55m
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc
  dnsNames:
  - linkerd-sp-validator.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-tap
  namespace: linkerd
spec:
  secretName: linkerd-tap-k8s-tls
  duration: 1h
  renewBefore: 55m
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-tap.linkerd.svc
  dnsNames:
  - linkerd-tap.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth



---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
spec:
  releaseName: linkerd
  chart:
    spec:
      chart: linkerd2
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: "2.9.4"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    installNamespace: false
    identity:
      issuer: 
        scheme: kubernetes.io/tls

    global:
      identityTrustAnchorsPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBjTCCATOgAwIBAgIQCUpxwX4dhgnJkJMvQPgQSjAKBggqhkjOPQQDAjAlMSMw
        IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMTA0MTkwNjAx
        NDFaFw0zMTA0MTcwNjAxNDFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
        dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzuEAIkiq4fLtjs4P
        NaFxxbJT7OQksd2jqsaZH1yBhjED4FULowzHDcuH1jNDb70I/RwjEjqDUtMZsKwj
        zlbGJaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
        VR0OBBYEFN52WEqetsTBb0YpcaDuGSVa7RZBMAoGCCqGSM49BAMCA0gAMEUCIGdP
        WYWVUEOyqJJhIqFjckplxOlb220MFkaaeBMyonadAiEA5y+rl+tVqm09m3YtqWoJ
        lqb6vttA0+CkN2ZshEFOYrM=
        -----END CERTIFICATE-----
    # webhook certificate keys
    proxyInjector:
      externalSecret: true 
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRAN8hG6bKJ1DCtHn7cKAsR+8wCgYIKoZIzj0EAwIwKDEm
        MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5
        MDcwNDA5WhcNMzEwNDE3MDcwNDA5WjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
        cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFkph8mK
        +V2vexEKfUJL12lLQ4a0SNVqimUUQopoQf8sAi6WpmBsGX9J9717G4dJm3EVwZ0z
        hFZVTb2j1gizCASjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBQEFAjQDjU5LFcEEynH+spZVy0u4jAKBggqhkjOPQQDAgNI
        ADBFAiEAl7YAYqVmg5ScnHzXZVSt4OnTdh05/1zYiiETUa629fsCIDsdGYUlZbTX
        Hq5bUg05i3jZfSIPHX7sPWBmEXW6igVB
        -----END CERTIFICATE-----
    
    profileValidator:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRAN8hG6bKJ1DCtHn7cKAsR+8wCgYIKoZIzj0EAwIwKDEm
        MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5
        MDcwNDA5WhcNMzEwNDE3MDcwNDA5WjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
        cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFkph8mK
        +V2vexEKfUJL12lLQ4a0SNVqimUUQopoQf8sAi6WpmBsGX9J9717G4dJm3EVwZ0z
        hFZVTb2j1gizCASjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBQEFAjQDjU5LFcEEynH+spZVy0u4jAKBggqhkjOPQQDAgNI
        ADBFAiEAl7YAYqVmg5ScnHzXZVSt4OnTdh05/1zYiiETUa629fsCIDsdGYUlZbTX
        Hq5bUg05i3jZfSIPHX7sPWBmEXW6igVB
        -----END CERTIFICATE-----
       
    tap:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRAN8hG6bKJ1DCtHn7cKAsR+8wCgYIKoZIzj0EAwIwKDEm
        MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5
        MDcwNDA5WhcNMzEwNDE3MDcwNDA5WjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
        cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFkph8mK
        +V2vexEKfUJL12lLQ4a0SNVqimUUQopoQf8sAi6WpmBsGX9J9717G4dJm3EVwZ0z
        hFZVTb2j1gizCASjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBQEFAjQDjU5LFcEEynH+spZVy0u4jAKBggqhkjOPQQDAgNI
        ADBFAiEAl7YAYqVmg5ScnHzXZVSt4OnTdh05/1zYiiETUa629fsCIDsdGYUlZbTX
        Hq5bUg05i3jZfSIPHX7sPWBmEXW6igVB
        -----END CERTIFICATE-----


