apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: psql
spec:
  releaseName: psql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "8.6.4"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  values:
    values:
    image:
      debug: true
    postgresqlExtendedConf:
      loggingCollector: on
      logDirectory: mylogs4pgbadger
      logMinDurationStatement: 0
    postgresqlUsername: kong
    postgresqlPassword: kong
    postgresqlDatabase: kong
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
