---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsRENDQVRxZ0F3SUJBZ0lSQU44aEc2YktKMURDdEhuN2NLQXNSKzh3Q2dZSUtvWkl6ajBFQXdJd0tERW0KTUNRR0ExVUVBeE1kZDJWaWFHOXZheTVzYVc1clpYSmtMbU5zZFhOMFpYSXViRzlqWVd3d0hoY05NakV3TkRFNQpNRGN3TkRBNVdoY05NekV3TkRFM01EY3dOREE1V2pBb01TWXdKQVlEVlFRREV4MTNaV0pvYjI5ckxteHBibXRsCmNtUXVZMngxYzNSbGNpNXNiMk5oYkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkZrcGg4bUsKK1YydmV4RUtmVUpMMTJsTFE0YTBTTlZxaW1VVVFvcG9RZjhzQWk2V3BtQnNHWDlKOTcxN0c0ZEptM0VWd1owegpoRlpWVGIyajFnaXpDQVNqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvCkFnRUJNQjBHQTFVZERnUVdCQlFFRkFqUURqVTVMRmNFRXluSCtzcFpWeTB1NGpBS0JnZ3Foa2pPUFFRREFnTkkKQURCRkFpRUFsN1lBWXFWbWc1U2NuSHpYWlZTdDRPblRkaDA1LzF6WWlpRVRVYTYyOWZzQ0lEc2RHWVVsWmJUWApIcTViVWcwNWkzalpmU0lQSFg3c1BXQm1FWFc2aWdWQgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUo3UTBlQjFKUm1VVnQ5ZnRHdGRTNnovZGEyNG9yUXFQMU02b0hiaHk2QThvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFV1NtSHlZcjVYYTk3RVFwOVFrdlhhVXREaHJSSTFXcUtaUlJDaW1oQi95d0NMcGFtWUd3WgpmMG4zdlhzYmgwbWJjUlhCblRPRVZsVk52YVBXQ0xNSUJBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: webhook-issuer-tls
  namespace: linkerd-viz
type: kubernetes.io/tls
---
# ignore if not using the viz extension
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: linkerd-viz
spec:
  ca:
    secretName: webhook-issuer-tls
---
# ignore if not using the viz extension
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap
  namespace: linkerd-viz
spec:
  secretName: tap-k8s-tls
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap.linkerd-viz.svc
  dnsNames:
  - tap.linkerd-viz.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---

# ignore if not using the viz extension
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-tap-injector
  namespace: linkerd-viz
spec:
  secretName: tap-injector-k8s-tls
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap-injector.linkerd-viz.svc
  dnsNames:
  - tap-injector.linkerd-viz.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---

#Add linkerd-viz
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
spec:
  releaseName: linkerd-viz
  chart:
    spec:
      chart: linkerd-viz
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      version: "2.10.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    installNamespace: false
    nodeSelector:
      cloud.google.com/gke-nodepool: linkerd-pool
    # webhook certificate keys
    tapInjector:
      externalSecret: true 
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRAN8hG6bKJ1DCtHn7cKAsR+8wCgYIKoZIzj0EAwIwKDEm
        MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5
        MDcwNDA5WhcNMzEwNDE3MDcwNDA5WjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
        cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFkph8mK
        +V2vexEKfUJL12lLQ4a0SNVqimUUQopoQf8sAi6WpmBsGX9J9717G4dJm3EVwZ0z
        hFZVTb2j1gizCASjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBQEFAjQDjU5LFcEEynH+spZVy0u4jAKBggqhkjOPQQDAgNI
        ADBFAiEAl7YAYqVmg5ScnHzXZVSt4OnTdh05/1zYiiETUa629fsCIDsdGYUlZbTX
        Hq5bUg05i3jZfSIPHX7sPWBmEXW6igVB
        -----END CERTIFICATE-----
       
    tap:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBlDCCATqgAwIBAgIRAN8hG6bKJ1DCtHn7cKAsR+8wCgYIKoZIzj0EAwIwKDEm
        MCQGA1UEAxMdd2ViaG9vay5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjEwNDE5
        MDcwNDA5WhcNMzEwNDE3MDcwNDA5WjAoMSYwJAYDVQQDEx13ZWJob29rLmxpbmtl
        cmQuY2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFkph8mK
        +V2vexEKfUJL12lLQ4a0SNVqimUUQopoQf8sAi6WpmBsGX9J9717G4dJm3EVwZ0z
        hFZVTb2j1gizCASjRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
        AgEBMB0GA1UdDgQWBBQEFAjQDjU5LFcEEynH+spZVy0u4jAKBggqhkjOPQQDAgNI
        ADBFAiEAl7YAYqVmg5ScnHzXZVSt4OnTdh05/1zYiiETUa629fsCIDsdGYUlZbTX
        Hq5bUg05i3jZfSIPHX7sPWBmEXW6igVB
        -----END CERTIFICATE-----