apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "v1.2.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    installCRDs: true
    image:
      pullPolicy: Always

    ingressShim:
      defaultIssuerName: "letsencrypt-prod"
      defaultIssuerKind: "ClusterIssuer"
      # defaultIssuerGroup: ""
    nodeSelector:
      kubernetes.io/os: linux

    prometheus:
      enabled: false

    webhook:
      replicaCount: 1

      image:
        repository: quay.io/jetstack/cert-manager-webhook
        pullPolicy: Always

    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        pullPolicy: Always
