apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: app-1
  namespace: flux-system
spec:
  # secretRef:
  #   name: gcr-credentials
  image: docker.io/nginx
  interval: 1m0s

---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: app-1
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app-1
  policy:
    numerical:
      order: asc
---